# Generated by Django 3.0.8 on 2020-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail_url', models.CharField(max_length=1000)),
                ('video_url', models.CharField(max_length=1000)),
                ('course_type', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], max_length=100)),
                ('course_length', models.CharField(max_length=100)),
            ],
        ),
    ]
